# Generated by Django 4.1.6 on 2023-02-23 08:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_bookmark_bookmark_unique_bookmark"),
    ]

    operations = [
        migrations.RenameField(
            model_name="bookmark",
            old_name="saved_at",
            new_name="modified_at",
        ),
    ]
